/* ================================================================
   OVL_ELISA v2 — la chat "Scrivi a Elisa" della dashboard.
   34 voci CURATE in 8 temi, scritte sulle fonti reali di Elisa-Know
   (Guida_Conoscenza_Elisa.md + database con le risposte verbatim di
   Elisa su Instagram + libro "La Vita Oltre il Velo"). Stile
   documentale: niente saluti, risposte per documentarsi, voce di
   Elisa. Matching: stemmer italiano + gate parole forti + soglia
   (porting fedele del software Elisa-Know).

   QUANDO IL SERVER "ELISA KNOW" SU COOLIFY SARÀ PRONTO:
   impostare REMOTE all'endpoint di chat (POST {question,history} →
   {answer,mode}). Le voci locali restano come riserva.
   ================================================================ */
window.OVL_ELISA=(function(){

  var REMOTE='';            /* endpoint del server conoscenza (vuoto = solo locale) */
  var REMOTE_TIMEOUT=6000;

  /* ---------- sicurezza: il guardrail viene SEMPRE prima di tutto ---------- */
  var CRISIS=/suicid|uccider|ammazzar|farla finita|togliermi la vita|non voglio (pi[uù] )?vivere|voglio morire|non ce la faccio pi[uù]|eutanasia|autoles|farmi del male/i;
  var CRISIS_MSG="Mi fermo un momento 💛 Da quello che scrivi potresti stare attraversando un dolore molto grande, e la cosa più importante adesso sei tu. Questo strumento non può sostituire l'aiuto di cui avresti bisogno in un momento così. Per favore parlane subito con qualcuno: in Italia puoi chiamare il 112 (emergenze), Telefono Amico Italia 02 2327 2327, o cercare il Servizio per la prevenzione del suicidio della tua zona. Non sei solo/a, e chiedere aiuto è un atto di coraggio.";

  /* ---------- avvertenza per le domande scritte a mano libera ---------- */
  var AVVISO="Ho riconosciuto le parole principali della tua domanda e ti porto la risposta più vicina tra gli insegnamenti di Elisa. Prendila come una risposta generale, per documentarti: qui non è Elisa a leggerti o a risponderti di persona.";
  var FALLBACK="Su questo non ho ancora una risposta pronta 🙏🏻 Questo spazio cresce piano piano, domanda dopo domanda. Prova a chiedermelo con parole diverse, oppure sfoglia i temi all'inizio della chat: forse la risposta che cerchi è già lì, sotto un'altra forma.";

  /* ---------- aggancio domanda → voce curata (stemming italiano) ---------- */
  var STOP={};
  ("come cosa dopo prima secondo della dello delle degli dell per con che chi quando dove cui sono essere stato elisa piu meno una uno due gli del dei nel nella alla allo agli sul sui sulla quale quali questo questa questi queste loro miei mia mio noi voi cose tutto tutti molto anche quindi perche poi gia ecco fare farsi "+
   "presente andare faccio riesco avanti vorrei voglio posso deve dovrei ancora sempre adesso niente qualcosa qualcuno proprio davvero magari invece senza dentro stesso stessa cioe allora insomma").split(" ").forEach(function(w){ STOP[w]=1; });
  var SYN={"lutto":["dolore","perdita","perdere","caro","morte","mancanza"],"colpa":["perdono","perdonare","rimorso","colpe","colpevole"],
    "morte":["morire","morto","trapasso","aldila","aldilà","defunto"],"morire":["morte","trapasso"],"segni":["segno","sogni","sogno","farfalle","profumo"],
    "sogni":["sogno","segni","onirico"],"reincarnazione":["reincarnarsi","vite","karma","rinascita"],"karma":["reincarnazione","debito","vite"],
    "paura":["ansia","timore","paure"],"medium":["medianita","medianità","sensitiva","tramite"],"medianita":["medium","sensitiva","tramite"],
    "consulto":["consulti","seduta","canalizzazione"],"energia":["frequenza","vibrazione","energetico"],"malattia":["malattie","malato","salute"],
    "spirito":["spiriti","anima","anime"],"perdono":["colpa","perdonare"],"depressione":["tristezza","sofferenza","buio"]};
  var SUF=["issimo","issima","amento","azione","zione","mente","eranno","iranno","arono","erono","irono","ando","endo","iamo","iate","arsi","ersi","irsi","are","ere","ire","ato","ata","ati","ate","ito","ita","iti","ite","uto","uta","uti","ute","ono","ano","amo","ete","ità","ore","ori","oso","osa","osi","ose","ico","ica","ici","che","i","e","a","o","ò","à"];
  function stem(w){
    w=(w||'').toLowerCase();
    w=w.replace(/(a|e|i)r(mi|ti|ci|vi|si|lo|la|li|le|ne|gli)$/, '$1re');
    for(var k=0;k<SUF.length;k++){
      var s=SUF[k];
      if(w.length>s.length+2 && w.slice(-s.length)===s)return w.slice(0,-s.length);
    }
    return w;
  }
  function stems(words){
    var out={};
    (words||[]).forEach(function(w){ if(w&&w.length>2)out[stem(w)]=1; });
    return out;
  }
  function contentWords(text){
    var m=(text||'').toLowerCase().match(/[a-zàèéìòù]+/g)||[];
    return m.filter(function(w){ return w.length>2 && !STOP[w]; });
  }
  function kw(query){
    var m=(query||'').toLowerCase().match(/[a-zàèéìòù]+/g)||[];
    var out=[];
    m.forEach(function(t){ if(t.length>3&&!STOP[t]&&out.indexOf(t)<0)out.push(t); });
    return out.slice(0,8);
  }
  function expand(terms){
    var out=terms.slice();
    terms.forEach(function(t){ (SYN[t]||[]).forEach(function(s){ if(out.indexOf(s)<0)out.push(s); }); });
    return out.slice(0,16);
  }
  function merge(a,b){ var o={},k; for(k in a)o[k]=1; for(k in b)o[k]=1; return o; }
  function overlap(a,b){ var n=0,k; for(k in a){ if(b[k])n++; } return n; }

  var QA_THRESHOLD=2;
  function prepara(){
    BANK.forEach(function(e){
      e._terms=merge(stems(contentWords(e.domande.join(" ")+" "+e.label)), stems(e.keys));
      e._gate=stems(e.keys);
    });
  }
  function qaMatch(question){
    var us=merge(stems(contentWords(question)), stems(expand(kw(question))));
    var any=false,k; for(k in us){any=true;break;}
    if(!any)return null;
    var best=null,bestsc=0;
    BANK.forEach(function(e){
      if(!overlap(us,e._gate))return;
      var sc=overlap(us,e._terms);
      if(sc>bestsc){bestsc=sc;best=e;}
    });
    return (best&&bestsc>=QA_THRESHOLD)?best:null;
  }

  /* ---------- risposta ---------- */
  function byId(id){
    for(var i=0;i<BANK.length;i++){
      if(BANK[i].id===id)return {answer:BANK[i].risposta,mode:"doc",tema:BANK[i].tema,label:BANK[i].label};
    }
    return null;
  }
  function localAnswer(question,history){
    question=(question||'').trim();
    if(!question)return {answer:"Scrivimi pure quello che hai nel cuore 💓",mode:"empty"};
    if(CRISIS.test(question))return {answer:CRISIS_MSG,mode:"safety"};
    var lastUser=''; (history||[]).forEach(function(m){ if(m.role==='user'&&m.text!==question)lastUser=m.text||''; });
    var rq=(question.split(/\s+/).length>4||!lastUser)?question:(lastUser+" "+question);
    var hit=qaMatch(rq);
    if(hit)return {answer:hit.risposta,mode:"faq",tema:hit.tema,avviso:AVVISO};
    return {answer:FALLBACK,mode:"empty"};
  }
  function rispondi(question,history,cb){
    if(CRISIS.test(question||'')){ cb({answer:CRISIS_MSG,mode:"safety"}); return; }
    if(!REMOTE){ cb(localAnswer(question,history)); return; }
    var done=false;
    var t=setTimeout(function(){ if(!done){done=true;cb(localAnswer(question,history));} },REMOTE_TIMEOUT);
    fetch(REMOTE,{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({question:question,history:history||[]})})
      .then(function(r){ if(!r.ok)throw 0; return r.json(); })
      .then(function(j){ if(!done){done=true;clearTimeout(t);cb(j&&j.answer?j:localAnswer(question,history));} })
      ['catch'](function(){ if(!done){done=true;clearTimeout(t);cb(localAnswer(question,history));} });
  }

  /* ---------- il menu dei temi (per la tendina in chat) ---------- */
  var MENU=[
    {t:"Il lutto e il dolore",icon:"🕯️",ids:["colpa_lutto","lasciare_andare","aiutare_caro","paura_morte"]},
    {t:"L'aldilà",icon:"🌅",ids:["dopo_morte","tre_giorni","dimensioni","luce_come","personalita_resta","animali"]},
    {t:"I legami che continuano",icon:"💞",ids:["rivedro_contatto","spiriti_ci_vedono","amore_coppia","famiglia_spirituale"]},
    {t:"Segni e sogni",icon:"🦋",ids:["segni_sogni","non_sogno","permessi_segni"]},
    {t:"Karma e reincarnazione",icon:"♻️",ids:["karma_cose","reincarnazione_scelta","ricordare_vite"]},
    {t:"La vita e le sue prove",icon:"🌱",ids:["energia_frequenza","cinque_ferite","malattia_senso","senso_vita","salute_mentale"]},
    {t:"I temi più delicati",icon:"🤍",ids:["fine_volontaria","male_giustizia","dio_religione"]},
    {t:"Elisa e la medianità",icon:"🔮",ids:["chi_e_elisa","metodo_connessione","medium_serio","scettici","sensibilita","consulto"]}
  ];

  /* ================================================================
     LE VOCI — fedeli alle fonti (libro, dirette, risposte reali di
     Elisa). Dove Elisa stessa non dà certezze, nemmeno noi.
     ================================================================ */
  var BANK=[

  /* ---------- IL LUTTO E IL DOLORE ---------- */
  {id:"colpa_lutto",tema:"Lutto & sensi di colpa",label:"Mi sento in colpa per chi ho perso",
   domande:["Mi sento in colpa per come è andata, per non essere stato presente quando il mio caro è morto. Ce l'ha con me?","Non ero presente quando è morto, non me lo perdono","La mattina che è morto avevamo litigato, è arrabbiato con me?","Mi sento in colpa per la morte di una persona cara","Come faccio a perdonarmi per quello che è successo"],
   keys:["colpa","perdono","perdonarmi","lutto","rimorso","litigato","presente"],
   risposta:"Il senso di colpa, nel lutto, è quasi sempre il primo a presentarsi: «non c'ero», «potevo fare di più», «l'ultima volta abbiamo litigato». Voglio dirti una cosa che ho visto tante volte: i nostri cari, da dove sono ora, non ci incolpano. Mai. Quel rimprovero che senti è tuo, nasce dall'amore e dal dispiacere — non da loro.\n\nSe ti aiuta, prova un piccolo esercizio: immagina di essere tu, dall'altra parte. Guarderesti la persona che ami con rancore per un momento in cui non eri nella stanza, o per una frase detta male in un giorno difficile? O la guarderesti con tenerezza, sapendo quanto bene le hai voluto? Ecco: è così che ti guarda lui.\n\nIl dolore di non aver «fatto in tempo» non te lo posso togliere, e non sarebbe nemmeno giusto dirti di non sentirlo. Ma può trasformarsi. Andare avanti non vuol dire dimenticare: l'amore che c'era non sparisce, gli dai solo una forma nuova. E puoi parlargli, sai? Anche adesso, ad alta voce o nel silenzio: a loro arriva tutto. Digli quello che non hai fatto in tempo a dire.\n\nUn'ultima cosa, col cuore: se questo peso ti toglie il sonno, ti chiude lo stomaco, ti accompagna ogni giorno, non tenerlo solo per te. A volte una mano professionale — qualcuno che ti aiuti a portarlo — fa davvero la differenza. Non sei in gara: datti il tempo che serve."},

  {id:"lasciare_andare",tema:"Lutto & lasciare andare",label:"Lasciare andare: andare avanti è tradire?",
   domande:["Cosa significa lasciare andare? Andare avanti è tradire chi ho perso?","Mi sento in colpa se torno a vivere e a sorridere dopo il lutto","Come si supera un lutto senza dimenticare","Rifarsi una vita è mancare di rispetto a chi non c'è più","Non riesco a lasciare andare il mio caro"],
   keys:["lasciare","tradire","tradimento","liberare","superare","sorridere","voltare"],
   risposta:"«Lasciare andare» è uno dei temi più centrali di tutto l'insegnamento di Elisa, e anche uno dei più fraintesi. Non significa dimenticare, non significa smettere di amare, e non significa che il legame finisce. Significa smettere di trattenere — il dolore, la colpa, l'idea che restare fermi nella sofferenza sia una prova d'amore.\n\nC'è una frase-simbolo che Elisa riporta dalle sue canalizzazioni, ed è il messaggio che gli spiriti stessi mandano più spesso a chi resta: «Non mi stai tradendo, mi stai liberando». Perché il nostro dolore, quando diventa una prigione, pesa anche a loro: lo percepiscono, e ciò che desiderano di più è vederci tornare a vivere.\n\nLa fedeltà a chi abbiamo amato non passa attraverso la rinuncia alla vita. Il dolore va attraversato — non scavalcato, non represso: attraversato — perché il dolore è trasformativo. Le lacrime non sono il problema: il problema è come decidiamo di vivere dopo.\n\nLasciare andare, quindi, è un atto d'amore doppio: libera te, che puoi dare al tuo amore una forma nuova, e libera il tuo caro, che può proseguire il suo cammino sapendoti in pace. Tornare a sorridere non è voltare le spalle a chi non c'è più: è il modo più alto di onorarlo. 🤍"},

  {id:"aiutare_caro",tema:"Lutto & sostegno",label:"Come posso aiutare il mio caro di là?",
   domande:["Come posso aiutare il mio caro che non c'è più?","Posso fare qualcosa per il mio defunto, pregare per lui?","Il mio caro ha bisogno di me dall'altra parte?","Come mando energia positiva a chi è nell'aldilà","Le preghiere arrivano ai defunti?"],
   keys:["aiutare","aiutarlo","aiutarla","pregare","preghiere","mandare","energie"],
   risposta:"Sì, possiamo fare molto per i nostri cari che sono passati oltre — e la risposta di Elisa su questo è sempre la stessa, ed è bellissima nella sua semplicità: il modo migliore per aiutarli è vivere bene noi.\n\nFunziona così: tra noi e loro resta un legame energetico. Ciò che proviamo arriva — Elisa racconta che i nostri pensieri rivolti a loro li raggiungono davvero, come messaggi. Se da questa parte mandiamo amore, gratitudine, vita vissuta, li accompagniamo nel loro percorso. Se mandiamo solo disperazione e colpa, appesantiamo anche loro: percepiscono il nostro dolore, e quel dolore li trattiene.\n\nIn concreto, ecco cosa puoi fare ogni giorno:\n\n• Parlagli. Ad alta voce o nel silenzio, racconta la tua giornata, le piccole cose: a loro arriva tutto, e non serve nessuna formula.\n• Perdona e perdonati. Il perdono — prima di tutto verso noi stessi — è una delle energie che più li libera.\n• Prega, se è nelle tue corde: la preghiera è energia rivolta a loro, e conta l'amore con cui la fai, non la forma.\n• Ricordalo con gioia. Elisa insegna che «ricordare significa guarire per lo spirito»: la memoria condivisa, le foto, i racconti, sono nutrimento, non ferita.\n• E soprattutto: torna a vivere. È la cosa che desiderano di più, ed è il regalo più grande che puoi fargli."},

  {id:"paura_morte",tema:"Paura della morte",label:"Ho paura della morte",
   domande:["Ho paura della morte, come la supero?","Ho paura di morire, di come morirò, della sofferenza","Perché abbiamo così tanta paura della morte?","Penso sempre alla morte e mi blocca","Come si affronta la paura della fine"],
   keys:["paura","morte","morire","terrore","fine","pensiero"],
   risposta:"La paura della morte è tra le cose più umane che esistano, e Elisa la affronta da un punto di vista preciso: «Parlare di aldilà e di vita dopo la morte, per me, non significa parlare di morte. Significa parlare di vita.»\n\nPrima cosa: perché la temiamo così tanto, se — come insegna Elisa — l'abbiamo già attraversata in altre vite? Perché non la ricordiamo. Ci incarniamo per vivere esperienze il più possibile vere, e per questo non ricordiamo ciò che c'è dall'altra parte: l'oblio è funzionale alla vita, ma è anche ciò che rende la morte un ignoto che spaventa.\n\nSeconda cosa, ed è il cuore: per Elisa la morte non è la fine della propria esistenza — è la fine di un'esperienza. Su questo, lei che raramente dà certezze, si espone in modo netto. Ciò che siamo continua; cambia la forma, non l'esistenza. Anche ciò che non si è fatto in tempo a vivere qui non va perduto.\n\nE la paura di come moriremo — la sofferenza, la malattia? Elisa è onesta: nessuno può sapere in anticipo come ce ne andremo, e avere una paura consapevole è già molto. Ma il punto vero è un altro: non lasciare che il pensiero della fine ci rovini il presente. Quel tempo non torna indietro. La consapevolezza che esiste un oltre serve proprio a questo: a vivere il qui e ora più pienamente, non con l'ansia del dopo. 💛"},

  /* ---------- L'ALDILÀ ---------- */
  {id:"dopo_morte",tema:"Aldilà: cos'è",label:"Cosa succede dopo la morte?",
   domande:["Cosa succede dopo la morte? Dove vanno i nostri cari quando muoiono?","Cosa c'è dopo la morte","Dove va l'anima dopo la morte","Cosa accade quando si muore","Dove si va e dove finiamo quando si muore","Esiste l'aldilà, com'è fatto"],
   keys:["morte","morire","muore","muoiono","aldilà","defunti","anima","trapasso"],
   risposta:"È la domanda delle domande, e ti rispondo con sincerità: non con una mappa precisa, perché sarebbe disonesto promettertela. Quello che sento, e che vivo nel mio lavoro, è che con la morte l'amore non finisce. Il corpo si spegne, ma ciò che siamo davvero continua.\n\nA me piace dire che l'aldilà è uno specchio: non un tribunale, non un luogo di condanna eterna. È piuttosto un riflesso di ciò che siamo stati e di come abbiamo amato. E non è qualcosa di fermo — è in continuo cambiamento, in evoluzione. I nostri cari, quando se ne vanno, non «spariscono» in un posto lontano: cambiano forma, e i legami autentici restano.\n\nNon tutti vivono questo passaggio allo stesso modo: dipende dal cammino di ciascuno, da ciò che ci si porta dietro, dai «cerchi» rimasti aperti. Ma la direzione, per chi ha amato, è verso la luce.\n\nCapisco che dietro questa domanda spesso ce n'è un'altra, più personale: «la persona che ho perso, sta bene?». Se è così, dimmelo pure, e ne parliamo. E se vuoi andare davvero a fondo, è proprio il cuore di quello che ho cercato di mettere nel mio libro, La Vita Oltre il Velo."},

  {id:"tre_giorni",tema:"Aldilà: cos'è",label:"I primi giorni dopo il trapasso",
   domande:["Cosa succede subito dopo la morte, nei primi giorni?","Cosa sono i tre giorni dopo il trapasso","Il mio caro è morto da poco, dove si trova adesso?","Subito dopo la morte lo spirito dove sta","Quanto tempo serve allo spirito per andare nella luce"],
   keys:["giorni","subito","appena","trapasso","poco","funerale","transizione"],
   risposta:"Nell'insegnamento di Elisa, subito dopo il trapasso c'è una fase di transizione — lei parla spesso dei «tre giorni» — in cui lo spirito consapevolizza ciò che è accaduto e comincia il distacco dalla dimensione terrena. Non è un cronometro rigido: è un passaggio, e ognuno lo vive a modo suo.\n\nCome lo vive, dipende molto da com'è stata la morte e da come si è vissuto. Se il trapasso è stato improvviso o traumatico, lo spirito può essere inizialmente confuso: ha bisogno di tempo per elaborare quello che è successo. Se invece c'è stata una preparazione — una malattia lunga, una vita consapevole — il passaggio può essere più morbido. In questa fase molti spiriti restano vicini ai loro cari: percepiscono il funerale, le lacrime, l'amore. Per questo Elisa ricorda che anche in quei primi giorni il nostro atteggiamento conta: parlargli, ringraziarlo, dirgli che può andare, lo aiuta davvero.\n\nPoi inizia il cammino vero e proprio: lo spirito si dirige verso la dimensione che corrisponde alla sua frequenza — quella di guarigione se ha ferite da elaborare, quella di Luce se è pronto (trovi la voce «Le dimensioni dell'aldilà» per il quadro completo).\n\nUna cosa importante se il tuo lutto è recente: se nei primi tempi non senti nulla, nessun segno, nessun sogno, non significa che il tuo caro non ci sia. Spesso è semplicemente presto — per lui e per te. Datti tempo, e dagliene. 🤍"},

  {id:"dimensioni",tema:"Aldilà: cos'è",label:"Le dimensioni dell'aldilà",
   domande:["Quali sono le dimensioni dell'aldilà?","Esistono inferno e paradiso? Cosa c'è al posto loro","Cos'è la dimensione buia o di guarigione","Cosa sono i piani alti","L'aldilà è uguale per tutti o ci sono livelli"],
   keys:["dimensioni","dimensione","buia","guarigione","piani","alti","inferno","purgatorio","paradiso","livelli"],
   risposta:"Nella visione che Elisa riporta dalle sue esperienze — e che racconta per esteso nel libro La Vita Oltre il Velo — l'aldilà non è un luogo unico, ma un insieme di dimensioni ordinate per frequenza energetica. Non si viene «assegnati» da un giudice: è la nostra stessa frequenza, costruita con emozioni, pensieri e azioni di una vita, a portarci dove siamo in sintonia.\n\n• La dimensione terrena: dove si trovano gli spiriti ancora «ancorati» alla Terra — in transizione, in visita ai loro cari, o trattenuti da un attaccamento, da cerchi rimasti aperti.\n\n• La dimensione buia, o di guarigione: la frequenza più bassa. Qui lo spirito rivive la propria vita come un film emotivo — sente ciò che ha provato e ciò che ha fatto provare. Non è un inferno e non è una punizione: è una fase di consapevolezza e guarigione, dura quanto serve, e nessuno vi resta per sempre.\n\n• La dimensione di Luce: amore incondizionato. Le due parole chiave che Elisa usa per descriverla sono equilibrio e sintonia (trovi la voce dedicata).\n\n• I piani alti: di questi Elisa dice solo che sono «energie così elevate che le parole ne sminuirebbero il senso».\n\nDue cose da portare a casa: nessuna dimensione è per sempre — l'evoluzione non si ferma mai, in nessun punto; e non esiste condanna eterna: «l'aldilà non è un tribunale. Il vero tribunale di noi stessi siamo noi.»"},

  {id:"luce_come",tema:"Aldilà: cos'è",label:"Com'è la dimensione della Luce?",
   domande:["Com'è la dimensione della luce?","Cosa si fa nella luce, ci si annoia?","Nell'aldilà si riposa per sempre?","Cosa sono le città spirituali e gli ospedali spirituali","Nella luce si sta tutti insieme?"],
   keys:["luce","città","ospedali","sintonia","equilibrio","riposo","beatitudine"],
   risposta:"«Due parole chiave per comprendere bene la luce sono equilibrio e sintonia.» Così la descrive Elisa: la dimensione di Luce è lo stato dell'amore incondizionato, dove lo spirito ritrova armonia con sé e con gli altri.\n\nMa attenzione a un'idea sbagliata: la Luce non è un «riposo eterno» passivo, una nuvola dove non accade più nulla. Dalle esperienze che Elisa riporta, nella Luce si resta attivi: ci sono le città spirituali, gli ospedali spirituali dove gli spiriti vengono curati e accompagnati, ci sono ruoli e compiti — il libro parla di veri e propri «ministeri» spirituali. Ci si ritrova con la propria famiglia spirituale, si continua a imparare, ci si prende cura di chi arriva.\n\nE c'è di più: anche nella Luce esistono livelli di consapevolezza. La pace raggiunta non è «la fine»: l'evoluzione non finisce mai, e gli spiriti continuano a crescere — Elisa racconta di averli visti cambiare, diventare «più luminosi» tra un incontro e l'altro.\n\nUn'ultima cosa, che è forse la più importante: la Luce non si impone e non «salva» nessuno con la forza. Tende la mano — e ogni spirito sceglie se prenderla. È un'immagine che torna sempre nelle parole di Elisa: l'amore, anche lassù, non obbliga mai. ✨"},

  {id:"personalita_resta",tema:"Aldilà: cos'è",label:"Il mio caro è ancora «lui»?",
   domande:["Il mio caro nell'aldilà è ancora lui, con il suo carattere?","La personalità resta dopo la morte?","Lo riconoscerò? Sarà cambiato?","Gli spiriti restano le persone che erano","Mio padre di là ha ancora il suo modo di fare?"],
   keys:["personalità","carattere","riconoscere","cambiato","ironia","modo"],
   risposta:"Sì — ed è una delle cose più belle e consolanti che Elisa riporta dalle sue canalizzazioni: la personalità resta. Il carattere, l'ironia, il modo di esprimersi, le passioni: chi era spiritoso resta spiritoso, chi era riservato si presenta con la sua riservatezza. Elisa lo dice spesso con una frase precisa: «Io li chiamo spiriti per farvi capire, ma sono assolutamente PERSONE» — e come persone, ognuno è diverso dall'altro.\n\nQuello che cambia, e cresce, è la consapevolezza. Dall'altra parte lo spirito vede la propria vita con uno sguardo più ampio: capisce dinamiche che da vivo non capiva, scioglie rigidità, matura. Per questo Elisa racconta che gli spiriti evolvono visibilmente — le è capitato di ritrovare lo stesso spirito a distanza di tempo e vederlo «cambiato di luce», più sereno, più consapevole. La personalità resta, la consapevolezza cresce: questa è la formula.\n\nQuindi sì: lo riconoscerai, e lui riconoscerà te. I legami autentici non si perdono nel passaggio — è uno dei punti più fermi di tutto ciò che Elisa insegna. La persona che ami non è stata «sostituita» da un'entità luminosa e impersonale: è lei, con in più la pace e la comprensione che qui, magari, non aveva fatto in tempo a trovare. 💞"},

  {id:"animali",tema:"Aldilà: cos'è",label:"Gli animali dopo la morte",
   domande:["Gli animali dopo la morte vanno nella luce?","Il mio cane mi aspetta nell'aldilà?","Dove vanno gli animali quando muoiono","Rivedrò il mio gatto? Gli animali hanno un'anima?","Gli animali possono mandarci segni o venirci a trovare"],
   keys:["animali","animale","cane","gatto","cucciolo","cagnolino"],
   risposta:"Per chi ha amato un animale, questa risposta di Elisa è una carezza: sì, gli animali vanno nella Luce — e anzi, ci vanno con un accesso più diretto del nostro. Non avendo i passaggi dimensionali intermedi che riguardano noi umani, si spostano tra le dimensioni molto più velocemente: il loro passaggio è semplice, pulito, senza i «cerchi da chiudere» che spesso trattengono noi.\n\nE di là come vivono? Elisa racconta ciò che le è stato mostrato dagli spiriti: gli animali domestici vivono nelle case con gli spiriti — sì, anche di là esistono le case — accanto a chi li ha amati o a chi si prende cura di loro. Gli animali delle altre specie hanno una sorta di grande foresta fatta per loro, dove ci sono spiriti che hanno proprio il compito di prendersene cura.\n\nPossono ancora venire da noi? Sì: chi è in Luce può fare visita alla Terra — non restarci a lungo, ma tornare. E quando un animale viene a trovarci, racconta Elisa, la sua energia si sente diversa, leggera.\n\nUna nota di onestà, perché è il modo di fare di Elisa: lei non canalizza gli animali. Tutto ciò che sa di loro le è stato detto e mostrato dagli spiriti umani durante le canalizzazioni. Quindi sì: il tuo cane, il tuo gatto, il tuo amico — c'è, sta bene, e il legame che vi univa non si è spezzato. 🐾"},

  /* ---------- I LEGAMI CHE CONTINUANO ---------- */
  {id:"rivedro_contatto",tema:"Aldilà & relazioni",label:"Rivedrò il mio caro? Posso parlargli?",
   domande:["Rivedrò il mio caro che non c'è più? Posso ancora comunicare con lui?","Rivedrò i miei cari dopo la morte","Posso comunicare con chi non c'è più","Come faccio a parlare con una persona morta","Riuscirò a riabbracciare i miei cari","Ci ricongiungeremo ai nostri cari"],
   keys:["rivedrò","rivedere","riabbracciare","abbracciare","comunicare","contatto","ricongiungere","comunicazione"],
   risposta:"Sì. Rivedere i nostri cari, ricongiungerci a loro, per me è una certezza — quello è un sì. La vera domanda, semmai, non è «se» li rivedremo, ma se potremo davvero stare con loro: e quello dipende dal cammino di ciascuno, da come abbiamo vissuto e amato.\n\nQuanto al comunicare, qui voglio essere onesta con te. Io faccio la medium, ma non voglio illuderti: il contatto vero non passa soltanto da una persona come me. Passa da te. Loro ci sono, e a loro arriva tutto quello che provi: puoi parlargli, raccontargli la tua giornata, dirgli ciò che ti è rimasto in gola. Non serve una formula.\n\nSpesso mi chiedono dei segni — una farfalla, un profumo, una canzone che torna. Non posso dirti con certezza «era lui»: non sarebbe onesto. Ma posso dirti che ciò che conta è quello che senti dentro. Se un segno ti fa stare un po' meglio, accoglilo: è un dono.\n\nE ricordati una cosa importante: a loro, dall'altra parte, sta a cuore soprattutto che noi stiamo bene, che non ci consumiamo nel dolore per la loro mancanza. Onorarli non vuol dire restare fermi nella sofferenza: vuol dire trasformare quell'amore e portarlo avanti nella vita."},

  {id:"spiriti_ci_vedono",tema:"Aldilà & conoscenza",label:"I nostri cari ci vedono? Sanno di noi?",
   domande:["I nostri cari defunti ci vedono? Sanno cosa ci succede?","Il mio caro mi sente quando gli parlo?","Gli spiriti sanno cosa facciamo, ci osservano?","I defunti soffrono vedendo il nostro dolore?","Mio padre vede i miei figli crescere?"],
   keys:["vedono","vede","sente","sentono","sanno","osservano","pensieri","arriva"],
   risposta:"Sì, ci percepiscono — e il «come» è una delle cose più affascinanti che Elisa racconta. Gli spiriti che sono in Luce possono tornare qui a farci visita: non restare a lungo, ma esserci, soprattutto nei momenti che contano. E anche quando non «scendono», ricevono ciò che proviamo: Elisa descrive che i nostri pensieri rivolti a loro arrivano come messaggi, quasi come filmati che li raggiungono dall'altra parte. Quando parli a tuo padre, a tua madre, al tuo compagno — arriva. Sempre. Senza bisogno di formule.\n\nQuesto non significa che ci «spiano» o che assistono a ogni istante della nostra giornata: il contatto segue i permessi e le energie di cui dispongono, e soprattutto segue l'amore — ci raggiungono dove e quando conta.\n\nE qui arriva la domanda che spesso si nasconde dietro questa: «ma allora soffrono, vedendo il nostro dolore?». La risposta di Elisa è sottile e importante: la differenza è la consapevolezza. Loro sanno ciò che noi spesso dimentichiamo — che ci rivedremo, che la separazione è un'esperienza e non una fine. Per questo non vivono la mancanza come la viviamo noi. Ciò che davvero li tocca è vederci consumati dal dolore: il nostro stare male è l'unica cosa che pesa loro. Ed è per questo che il regalo più grande che possiamo fargli è semplice: vivere. 💛"},

  {id:"amore_coppia",tema:"Aldilà & relazioni",label:"L'amore di coppia continua?",
   domande:["L'amore di coppia continua nell'aldilà?","Ho perso mio marito: di là è ancora mio marito?","Se mi rifaccio una vita con un'altra persona, tradisco chi ho perso?","Nell'aldilà ci si innamora ancora?","Ritroverò il mio compagno, saremo ancora una coppia?"],
   keys:["marito","moglie","compagno","compagna","coppia","innamorare","risposare","fidanzato","fidanzata"],
   risposta:"L'amore vero non si spezza con il trapasso: questo è uno dei punti fermi di ciò che Elisa riporta. I legami autentici — quelli costruiti con amore reale, non con l'abitudine o il possesso — restano, e ci si ritrova. Molte coppie appartengono alla stessa famiglia spirituale: anime che si sono già incontrate e che si reincontreranno.\n\nMa l'aldilà cambia la forma dell'amore: di là l'amore non è possesso. Non esistono gelosia, esclusività imposta, «sei mio». Esiste un amore più largo, fatto di sintonia. Per questo il tuo caro, dall'altra parte, non vive la vostra storia come qualcosa di interrotto: la custodisce, e insieme ti guarda con una libertà che qui è difficile perfino immaginare.\n\nE qui arriva la domanda che brucia di più: «se mi rifaccio una vita, lo tradisco?». La risposta che gli spiriti stessi mandano, nelle canalizzazioni di Elisa, è netta: no. «Non mi stai tradendo, mi stai liberando.» Ciò che desiderano è vederci vivere, non vederci fermi a custodire un altare di dolore. Un nuovo amore non cancella quello che c'è stato: il cuore non funziona a sostituzione, funziona ad ampliamento.\n\nQuindi: sì, vi ritroverete. Sì, quel legame conta ancora. E sì, hai il diritto — quasi il compito — di continuare a vivere e anche di amare ancora, se la vita te lo porta. Le due cose non si escludono: si benedicono a vicenda. 💞"},

  {id:"famiglia_spirituale",tema:"Aldilà & relazioni",label:"La famiglia spirituale e le anime",
   domande:["Cos'è la famiglia spirituale?","Esistono le anime gemelle?","Le anime si reincontrano vita dopo vita?","Cos'è il gruppo di anime a cui apparteniamo","Le persone importanti della mia vita le ho già conosciute in altre vite?"],
   keys:["famiglia","spirituale","anime","gemelle","gruppo","animico"],
   risposta:"La famiglia spirituale è uno dei concetti più ricorrenti nell'insegnamento di Elisa: è il gruppo di anime a cui apparteniamo, legami animici profondi che si reincontrano vita dopo vita, e che di là ci accolgono quando torniamo.\n\nFunziona così: non viaggiamo da soli. Ci sono anime con cui abbiamo un legame che precede questa vita — e spesso le riconosciamo: sono quelle persone con cui «ci siamo capiti subito», quelle relazioni che sembrano avere una profondità inspiegabile, e a volte anche quelle che ci mettono di fronte alle prove più dure. Perché la famiglia spirituale non è solo dolcezza: le anime a noi legate possono scegliere di accompagnarci anche attraverso esperienze difficili, quando servono alla crescita di entrambe.\n\nQuando uno spirito torna nella Luce, la sua famiglia spirituale è lì: è uno degli elementi che ricorrono in quasi tutte le canalizzazioni di Elisa — chi se ne va viene accolto, accompagnato, atteso. E uno dei tre motivi per cui un'anima sceglie di reincarnarsi è proprio aiutare la propria famiglia spirituale (trovi la voce sulla reincarnazione).\n\nE le «anime gemelle»? Elisa usa questo linguaggio con prudenza, senza la retorica romantica che ci si è costruita sopra: più che «l'altra metà perfetta», esistono anime profondamente affini dentro lo stesso gruppo, legami speciali che attraversano le vite. L'amore conta più dell'etichetta. ✨"},

  /* ---------- SEGNI E SOGNI ---------- */
  {id:"segni_sogni",tema:"Segni & sogni",label:"Come riconosco i segni e i sogni veri?",
   domande:["Come riconosco i segni dei miei cari defunti? E i sogni in cui li vedo sono reali contatti?","Come capisco se un segno viene da chi non c'è più","Ho sognato il mio caro defunto, era davvero lui?","I sogni con i defunti sono reali","Ho sognato un mio caro defunto, è un messaggio reale?","Le farfalle e i profumi sono segni dei defunti"],
   keys:["segni","segno","sogni","sogno","sognato","sognare","messaggio","farfalla","farfalle","profumo"],
   risposta:"I segni e i sogni sono tra le cose che mi chiedete più spesso, e li capisco bene: nascono dal bisogno di sentire che chi amiamo è ancora lì.\n\nComincio dall'onestà: io non posso dirti con certezza «quella farfalla era lui», «quel profumo era lei». Non sarebbe corretto. Quello che posso dirti è che il segno più vero non è fuori, ma dentro: è ciò che senti tu quando accade. Se un dettaglio — una canzone che torna, un numero, un animale che si ferma vicino — ti scalda il cuore e ti fa sentire vicino chi hai perso, accoglilo come un dono, senza bisogno di «prove».\n\nI sogni sono un discorso a parte. Ci sono i sogni che sono solo elaborazione nostra, del nostro dolore; e poi ci sono i sogni reali, i veri contatti. Di solito questi ultimi si riconoscono perché sono nitidi, restano impressi a lungo, lasciano una sensazione di pace più che di angoscia, e spesso portano un messaggio semplice. Distinguere gli uni dagli altri l'ho spiegato per bene nel libro e nelle mail di approfondimento, perché in poche righe rischierei di banalizzarlo.\n\nIl mio consiglio, intanto, è questo: non andare a caccia di segni con ansia. Vivi, parla ai tuoi cari, e lascia che siano loro a trovare il modo. Spesso arrivano proprio quando smettiamo di pretenderli."},

  {id:"non_sogno",tema:"Segni & sogni",label:"Perché non sogno il mio caro?",
   domande:["Perché non sogno mai il mio caro defunto?","Non ho mai sognato mia madre da quando è morta, perché?","Tutti sognano i loro cari tranne me","Il mio caro non mi manda sogni né segni, si è dimenticato di me?","Perché non ricevo niente dal mio caro"],
   keys:["sogno","sognare","sognato","ricevo","manda","dimenticato"],
   risposta:"Questa domanda porta spesso con sé una ferita nascosta — «perché agli altri sì e a me no? si è dimenticato di me?» — quindi partiamo da qui: no. Non sognarlo non significa che non ti sia vicino. Su questo Elisa è chiarissima.\n\nLe ragioni possono essere diverse, e lei le spiega con onestà, senza inventare certezze:\n\n• Il sogno «costa» tantissima energia. Per uno spirito, farsi vedere in sogno è una delle forme di contatto più impegnative che esistano: molti non riescono nemmeno a mostrarsi in volto, e fanno percepire solo la loro presenza. Non è questione di volontà: è questione di possibilità.\n\n• A volte siamo noi a chiudere i canali, senza volerlo. Il dolore troppo acuto, l'ansia di riceverli, il sonno agitato: tutto questo può rendere difficile il passaggio. È uno dei paradossi del lutto — più disperatamente li cerchiamo, più il canale si stringe.\n\n• E ci sono i permessi: il contatto in sogno è regolato anche da una tutela che protegge noi e loro. A volte un sogno non arriva perché, semplicemente, non è ancora il momento giusto per riceverlo.\n\nIntanto guarda i segni, che richiedono molta meno energia: sono il loro modo più semplice di dire «ci sono ancora». E continua a parlargli — quello arriva sempre, anche senza risposta visibile. I sogni, quando potranno, arriveranno: spesso proprio quando avremo smesso di pretenderli. 🤍"},

  {id:"permessi_segni",tema:"Segni & sogni",label:"I «permessi»: posso chiedere un segno?",
   domande:["Posso chiedere un segno al mio caro?","Cosa sono i permessi di cui parla Elisa?","Perché i defunti non possono comunicare sempre","Come funzionano i segni, ci sono delle regole?","Se chiedo un segno me lo manderanno?"],
   keys:["permesso","permessi","chiedere","segnale","regole"],
   risposta:"Sì, puoi chiedere un segno — ma per capire cosa aspettarti serve conoscere uno dei concetti più importanti che Elisa riporta: i permessi.\n\nIl contatto tra le dimensioni non è un «tutto libero»: è regolato. I segni, i sogni, le visite — tutto passa attraverso permessi che arrivano dai piani più alti, e la frase di Elisa che riassume il principio è questa: «Il permesso non è mai un'imposizione». È una tutela, nei due sensi: protegge noi, che potremmo non essere pronti a ricevere certi contatti, e protegge loro, che hanno un percorso da fare e non possono consumarsi nel guardare indietro.\n\nDentro queste regole, però, c'è una gerarchia di «costi»: i segni richiedono molta meno energia dei sogni. Per questo sono il canale più usato — una farfalla, una piuma, un numero che ricorre, un profumo improvviso, una canzone al momento giusto. Elisa li descrive come il loro modo di dire «ci sono ancora».\n\nQuindi: chiedi pure, con semplicità, parlandogli come hai sempre fatto. Ma poi — e questo è il punto che Elisa ripete sempre — lascia andare la pretesa. Non metterti a caccia di segni con ansia, non trasformare ogni coincidenza in un esame: quell'ansia chiude proprio il canale che vorresti aprire. Vivi, e lascia che siano loro a trovare il modo e il momento. Di solito arrivano quando smettiamo di aspettarli — e quando arrivano, lo senti dentro, senza bisogno di prove. 🦋"},

  /* ---------- KARMA E REINCARNAZIONE ---------- */
  {id:"karma_cose",tema:"Karma & reincarnazione",label:"Cos'è davvero il karma?",
   domande:["Cos'è il karma?","Il karma è una punizione per le vite passate?","Cosa significa karma per Elisa","Le cose brutte che mi succedono sono colpa del karma?","Come funziona il karma nella nostra vita"],
   keys:["karma","karmico","karmica","bagaglio"],
   risposta:"Partiamo dalla definizione di Elisa, che spazza via subito l'equivoco più diffuso: «Il karma non è una condanna. È il nostro bagaglio energetico — in questa vita e in quelle precedenti.»\n\nQuindi no: il karma non è una punizione, non è un debito che qualcuno ti fa pagare, non è un tribunale cosmico che tiene il conto dei tuoi errori. È molto più semplice e molto più serio: è ciò che ci portiamo dietro. Ogni emozione vissuta, ogni azione fatta o subita, ogni nodo non sciolto — in questa vita e in quelle precedenti — forma un bagaglio energetico che viaggia con noi. Non un macigno per schiacciarci: un bagaglio da conoscere, aprire, alleggerire.\n\nCome funziona in pratica? Per causa-effetto, non per castigo. Certe situazioni che si ripetono, certe relazioni che sembrano «già scritte», certe prove che tornano: spesso sono ripercussioni karmiche — energie che chiedono di essere riequilibrate. Elisa è precisa anche su questo: nemmeno la cosiddetta «malattia karmica» è una punizione, è un riequilibrio (trovi la voce sulla malattia per il quadro completo).\n\nE soprattutto: il karma non cancella mai il libero arbitrio. Non c'è un destino unico già scritto — c'è una ramificazione di possibilità, e siamo noi, con le scelte di ogni giorno, a decidere quale strada imbocchiamo. Il bagaglio lo portiamo, ma il cammino lo scegliamo. Lavorare su di sé, perdonare, sciogliere i nodi: questo è alleggerire il karma. ♻️"},

  {id:"reincarnazione_scelta",tema:"Karma & reincarnazione",label:"La reincarnazione: perché si torna?",
   domande:["La reincarnazione esiste? Come funziona?","Perché un'anima sceglie di reincarnarsi","Siamo obbligati a tornare sulla terra?","Il mio caro defunto si reincarnerà presto e non lo troverò più?","Quante volte ci si reincarna"],
   keys:["reincarnazione","reincarnarsi","reincarna","rinascere","rinascita","tornare"],
   risposta:"Sì, nella visione che Elisa riporta la reincarnazione esiste — ma con una caratteristica che cambia tutto: è una scelta. Mai un obbligo, mai una ruota cieca che ci risucchia. Lo spirito decide se e quando tornare, e lo fa per tre motivi fondamentali:\n\n1. L'evoluzione personale: tornare per attraversare esperienze che facciano crescere l'anima — anche quelle difficili, scelte prima di incarnarsi come occasioni di comprensione.\n2. Aiutare la propria famiglia spirituale: a volte un'anima torna soprattutto per accompagnare altre anime a cui è legata, nel loro cammino.\n3. Una missione collettiva: contribuire a qualcosa che riguarda tutti, portare luce in un momento storico, servire un disegno più grande del singolo.\n\nE c'è una precisazione importante che Elisa fa sempre, perché tocca una paura concreta di chi è in lutto: «se il mio caro si reincarna, non lo troverò più?». La reincarnazione è lenta e ponderata — non si torna domani. Lo spirito ha i suoi tempi di guarigione, di evoluzione, di scelta; e i legami autentici non si perdono nei passaggi: la famiglia spirituale si ritrova.\n\nUltima cosa: anche prima di incarnarsi non si sceglie un copione rigido. Elisa parla di destino multilineare — una ramificazione di possibilità, dentro la quale il libero arbitrio resta sempre nostro. Si sceglie il viaggio, non ogni singolo passo. ♻️"},

  {id:"ricordare_vite",tema:"Karma & reincarnazione",label:"Perché non ricordiamo le altre vite?",
   domande:["Perché non ricordiamo le vite precedenti?","Si possono ricordare le vite passate?","Se mi sono già reincarnato perché non ricordo nulla","Il déjà vu è un ricordo di un'altra vita?","Dall'altra parte ricorderemo tutto?"],
   keys:["ricordare","ricordiamo","ricordo","vite","precedenti","passate","memoria"],
   risposta:"La risposta di Elisa a questa domanda è di una semplicità disarmante: non ricordiamo perché dobbiamo vivere davvero. «Ci incarniamo per vivere esperienze il più possibile vere, e per questo non ricordiamo ciò che c'è dall'altra parte.»\n\nPensaci: se ricordassimo ogni vita precedente, ogni scelta fatta prima di nascere, ogni certezza sull'aldilà — questa vita sarebbe una recita a copione conosciuto. Niente avrebbe il peso, il rischio, la verità che hanno le cose vissute per la prima volta. L'oblio non è un difetto del sistema: è la condizione che rende l'esperienza autentica. È il velo — quello che Elisa chiama il velo di Maya — che separa le dimensioni e ci permette di essere davvero qui.\n\nQuesto oblio ha un prezzo, e Elisa lo riconosce con onestà: è anche il motivo per cui temiamo la morte. Non ricordando di averla già attraversata, la viviamo come un salto nel buio assoluto.\n\nMa c'è l'altra metà della storia: dall'altra parte si ricorda. Lo spirito, liberato dal velo, ritrova la memoria del suo cammino — e per Elisa questa memoria è preziosa: «Ricordare significa guarire per lo spirito. Più lo spirito ricorda, più lo spirito può guarire.»\n\nE i frammenti che a volte affiorano qui — déjà vu, affinità inspiegabili, paure senza origine? Possono essere echi del bagaglio che portiamo. Elisa invita a non costruirci sopra castelli: accoglili come indizi del fatto che sei un viaggiatore di lungo corso, e torna a vivere questa vita — è lei, adesso, il tuo compito. ✨"},

  /* ---------- LA VITA E LE SUE PROVE ---------- */
  {id:"energia_frequenza",tema:"Energia & emozioni",label:"Siamo energia: cosa significa?",
   domande:["Cosa significa che siamo energia?","Cos'è la frequenza energetica","Come alzo la mia frequenza?","Il pessimismo e la negatività attirano cose negative?","Come non farsi trascinare dalla negatività degli altri"],
   keys:["energia","frequenza","vibrazione","negatività","pessimismo","alzare","vibrare"],
   risposta:"È la base di tutto l'insegnamento di Elisa, il punto da cui parte ogni altra cosa: noi siamo energia. Non come metafora poetica — come descrizione di ciò che siamo. E ogni persona ha una sua frequenza energetica, una vibrazione formata da ciò che vive dentro: le emozioni, i pensieri, le azioni, le relazioni che coltiva.\n\nPerché è così importante? Per due ragioni. La prima riguarda questa vita: «Cambiare la nostra frequenza è la base per riuscire a comprendere e a consapevolizzare tutto il resto» — la frequenza determina come stiamo, cosa attiriamo, come leggiamo ciò che ci accade. La seconda riguarda l'oltre: è la frequenza con cui viviamo a determinare la dimensione dell'aldilà in cui ci troveremo in sintonia. Non un giudice: la nostra stessa vibrazione.\n\nE come si lavora sulla frequenza, in pratica? Il principio più concreto che Elisa ripete è questo: non nutrire la frequenza bassa. Se rispondi alla rabbia con la rabbia, al giudizio col giudizio, alla paura con la paura, non stai combattendo quell'energia — la stai alimentando. Il lavoro vero è accorgersi e scegliere di non darle da mangiare.\n\nAttenzione però a non trasformare tutto in colpa («sto male, quindi attiro cose brutte»): le emozioni basse fanno parte di noi. Elisa non chiede di condannarle, ma di riconoscerle e trasformarle — è esattamente il lavoro dell'osservatore, e degli esercizi del Cammino Interiore che trovi in quest'area. ⚡"},

  {id:"cinque_ferite",tema:"Crescita interiore",label:"Le 5 ferite dell'anima e l'osservatore",
   domande:["Cosa sono le cinque ferite dell'anima?","Cos'è l'osservatore di cui parla Elisa","Rifiuto abbandono umiliazione tradimento ingiustizia: cosa significano","Come riconosco la mia ferita dell'anima","Come si guariscono le ferite interiori"],
   keys:["ferite","ferita","rifiuto","abbandono","umiliazione","tradimento","ingiustizia","osservatore"],
   risposta:"Le cinque ferite dell'anima sono uno degli strumenti che Elisa usa di più per il lavoro interiore. Sono: il rifiuto, l'abbandono, l'umiliazione, il tradimento e l'ingiustizia.\n\nOgnuno di noi ne porta almeno una, di solito formata nell'infanzia e poi rinforzata dalla vita. E le ferite hanno un comportamento preciso: si attivano. Qualcuno dice una frase, accade una situazione — e la reazione che esplode dentro di noi è sproporzionata rispetto al fatto: non stiamo reagendo a oggi, stiamo reagendo alla ferita antica che quel fatto ha toccato. Riconoscere qual è la propria ferita dominante è già metà del lavoro: spiega tanti automatismi, tante relazioni che si ripetono, tanti giudizi che ci diamo.\n\nE qui entra lo strumento principe: l'osservatore. È la capacità di guardarsi dall'esterno nel momento esatto in cui la ferita si attiva. Non reprimere l'emozione, non esserne travolti: vederla. Fare un passo di lato e dire «ecco, si è acceso qualcosa: cosa sta toccando davvero?». In quel passo di lato c'è tutta la libertà possibile: smetti di essere l'emozione e torni a essere chi la attraversa.\n\nLe ferite non si «cancellano»: si conoscono, si ascoltano, si trasformano — con pazienza, senza condanna, perché anche la nostra ombra fa parte di noi. È esattamente il lavoro che fai nel Giornaliero di quest'area: lo Spazio Emotivo e l'Osservatorio Interiore sono nati per questo. 🌱"},

  {id:"malattia_senso",tema:"Malattia & spiritualità",label:"La malattia ha un senso spirituale?",
   domande:["La malattia ha un significato spirituale?","Perché ci si ammala, è il karma?","La mia malattia è una punizione?","Le emozioni represse fanno ammalare?","Che senso ha la sofferenza della malattia"],
   keys:["malattia","malattie","tumore","cancro","malato","ammalata","ammalarsi"],
   risposta:"Su questo tema Elisa è insieme chiara e prudentissima, e la prudenza fa parte della risposta.\n\nNella sua visione, dietro una malattia possono esserci tre chiavi diverse:\n\n1. Una scelta evolutiva fatta prima di incarnarsi: alcune anime scelgono esperienze difficili come occasioni di crescita — per sé e per chi sta loro accanto.\n2. Una somatizzazione: emozioni represse a lungo — rabbia, dolore, paura mai ascoltati — che trovano nel corpo l'unica via per farsi sentire.\n3. Oppure, semplicemente, un evento terreno: il corpo è materia, e la materia si ammala. Non tutto ha un significato nascosto.\n\nE la cosiddetta «malattia karmica»? Anche qui Elisa smonta l'idea più tossica: non è mai una punizione — è un riequilibrio. Nessuno «si merita» la malattia. Mai.\n\nMa la parte più importante della risposta è il come Elisa tratta questo tema con chi soffre davvero. Quando una persona malata le chiede «perché proprio a me?», lei non risponde con spiegazioni karmiche fredde — dice apertamente che sarebbe irrispettoso. Arriva ad ammettere: «Non so dirti il perché, sinceramente. Ma sono sicura che dietro tutto ciò che ci capita, nel bene e nel male, c'è sempre un insegnamento.»\n\nE un confine non negoziabile: la lettura spirituale non sostituisce mai la medicina. Curarsi, fare prevenzione, seguire i medici — sempre. La visione spirituale può accompagnare il percorso di cura e dargli un senso: mai prenderne il posto. 🤍"},

  {id:"senso_vita",tema:"Senso della vita",label:"Perché siamo qui? Il senso della vita",
   domande:["Qual è il senso della vita?","Perché siamo qui, perché nasciamo?","Che scopo ha la nostra esistenza","La vita è solo sofferenza, che senso ha?","Cosa veniamo a fare su questa terra"],
   keys:["senso","scopo","nascere","nascita","missione","esistenza"],
   risposta:"Per Elisa, nascere è molto più che arrivare qui: è il momento in cui un'anima accetta di entrare in un'esperienza fatta di corpo, emozioni, legami, prove e possibilità — per attraversare qualcosa che la aiuti a crescere, comprendere, evolvere. Ogni nascita porta con sé qualcosa di sacro, anche quando la vita ci mette davanti fatiche e ferite. «Nessuno nasce solo per esserci: nasciamo per fare un cammino.»\n\nLa vita, in questa visione, è un viaggio dell'anima attraverso la materia: lo spirito viene qui per conoscersi — nel bene e nel male, nella luce e nell'ombra — in un modo che solo l'esperienza concreta, col suo peso e la sua verità, rende possibile. Per questo Elisa dice che la materia è esperienza, non destinazione: la vita non è qualcosa da trattenere a ogni costo, è qualcosa da attraversare. Non finisce: cambia forma.\n\nAttenzione a un fraintendimento: quando Elisa chiama la vita «un'esperienza» o perfino «una simulazione» dell'anima, non sta dicendo che è finta o che non conta. Al contrario — lo precisa lei stessa: ogni singola esperienza è preziosa, ogni affetto è reale e continua. Proprio perché siamo qui per questo, ogni giorno vissuto, amato, perfino sofferto, vale.\n\nE il senso, allora? Non è scritto in cielo una volta per tutte: si costruisce camminando — evolvendo, amando, sciogliendo i propri nodi, aiutando le anime che viaggiano con noi. Il senso della vita, per Elisa, è il cammino stesso. 🌱"},

  {id:"salute_mentale",tema:"Salute mentale & spiritualità",label:"Spiritualità e salute mentale",
   domande:["La spiritualità può sostituire lo psicologo?","Soffro di depressione, la spiritualità mi può aiutare?","Elisa dà consigli psicologici?","Spiritualità e psicologia possono andare insieme?","La depressione è un male dell'anima?"],
   keys:["depressione","psicologo","psicologa","psicologico","mentale","terapia","psichiatra"],
   risposta:"Su questo tema Elisa ha una posizione netta, ripetuta mille volte, ed è bene dirla subito: la spiritualità non sostituisce mai il percorso medico e psicologico. Sono strade complementari — possono camminare insieme, e insieme funzionano meglio — ma una non prende il posto dell'altra.\n\nElisa lo dice di sé con un'onestà rara nel suo ambiente: «Io non posso darti consigli a livello psicologico, perché non ho qualifiche.» Non è una formula di rito: è il suo modo di lavorare. Collabora stabilmente con una psicologa, e dopo i consulti più difficili indirizza lei stessa le persone al supporto professionale. Sulla possibilità di «salvare» qualcuno con la sola spiritualità è disarmante: «Da sola non penso di riuscirci. Il consulto più l'aiuto psicologico fa una differenza enorme.»\n\nQuesto non significa che la dimensione spirituale non c'entri nulla con la sofferenza psichica. Elisa — che ha la depressione grave in famiglia e ne parla apertamente — invita a non etichettare mai nessuno come «causa persa»: ha visto quanto contino la presenza, la pazienza, l'avere qualcosa per cui lottare. E riconosce che in certi dolori dell'anima può esserci anche una domanda evolutiva («io chi sono?») — ma avverte: dirlo a chi sta soffrendo acutamente rischia di banalizzare, perché quella comprensione va vissuta, non spiegata.\n\nQuindi, in pratica: se stai attraversando ansia, depressione, un dolore che non passa — chiedi aiuto professionale, prima di tutto. E se vuoi, accanto a quello, il lavoro spirituale e interiore può accompagnarti: come alleato, mai come scorciatoia. 🤍"},

  /* ---------- I TEMI PIÙ DELICATI ---------- */
  {id:"fine_volontaria",tema:"Fine volontaria & lutto",label:"Chi se ne va per troppa sofferenza",
   domande:["Cosa succede a chi si toglie la vita?","Chi se ne va volontariamente raggiunge la luce?","Ho perso una persona che si è tolta la vita, dove si trova ora? Come posso aiutarla?","Chi muore per fine volontaria viene punito nell'aldilà?","Mio fratello se n'è andato volontariamente, sta bene?"],
   keys:["volontaria","volontariamente","tolto","tolta","gesto"],
   risposta:"Questo è uno dei temi a cui Elisa dedica più cura, e la prima cosa che dice è la più importante: nessuna condanna. Chi se ne va per troppa sofferenza non viene punito, non è escluso dalla Luce, non è perduto. «Sì, tutti possono raggiungere la luce: ho fatto tante canalizzazioni con spiriti così, e molti li ho visti in luce.»\n\nIl loro percorso, però, ha delle particolarità che Elisa descrive con onestà. Nei primi tempi questi spiriti sono spesso confusi: la morte è stata traumatica e serve tempo per elaborare che non era la soluzione. Portano spesso un senso di colpa fortissimo — percepiscono il dolore di chi hanno lasciato, e quel dolore li fa stare peggio. E c'è la scoperta più dura: ciò che non si è elaborato qui, dall'altra parte non sparisce — si ritrova, a volte perfino più intenso. Per questo il loro cammino di guarigione è di solito più lungo. Ma mai in solitudine: la Luce tende la mano anche a loro, sempre, e i loro cari spirituali li accompagnano.\n\nCosa possiamo fare noi, da questa parte? Le indicazioni di Elisa sono concrete: perdonarli — è la cosa di cui hanno più bisogno; parlargli, condividere anche le piccole cose, dirgli di andare avanti e di non arrendersi; e non farne una colpa, né a loro né a noi stessi. A loro arriva tutto.\n\n💛 E una cosa importante, detta col cuore: se questo tema ti tocca perché sei tu a portare un dolore così grande, non tenerlo per te. Parla subito con qualcuno: in Italia ci sono il 112 e Telefono Amico Italia (02 2327 2327). Chiedere aiuto è un atto di coraggio."},

  {id:"male_giustizia",tema:"Male & giustizia nell'aldilà",label:"Chi ha fatto del male: c'è giustizia?",
   domande:["Cosa succede a chi ha fatto del male nella vita?","Esiste una giustizia divina per i cattivi?","Anche un assassino va nella luce?","Chi mi ha fatto soffrire la pagherà nell'aldilà?","Le persone crudeli hanno un'anima?"],
   keys:["male","giustizia","assassino","cattivi","crudeli","omicidio","pagherà","punizione"],
   risposta:"È la domanda-sfida che viene fatta più spesso a Elisa, e la sua risposta è un'immagine precisa: «Nell'aldilà non esiste un tribunale: esiste uno specchio.»\n\nCosa significa? Che nessuno «assolve» nessuno — ma nessuno nemmeno condanna dall'alto. Ogni anima si confronta con ciò che è, ciò che ha fatto e ciò che ha generato. Chi ha ferito profondamente scende in una realtà dura e lenta — la dimensione più bassa, quella di guarigione — dove rivive la propria vita come un film emotivo: sente, su di sé, il dolore che ha causato. Non è una vendetta: è la consapevolezza piena, che è la forma più vera di giustizia. E quel percorso è tutto fuorché una scappatoia.\n\nMa — ed è il punto che fa più discutere — la Luce non è preclusa a nessuno. «L'Amore non chiude porte per sempre»: anche chi ha fatto il male può, un giorno, dopo un cammino lunghissimo di consapevolezza, scegliere di farsi aiutare. Elisa sa che molti non accettano questa visione, e risponde con la sua onestà di sempre: «Io riporto ciò che vivo: se la realtà è questa, possiamo farci poco. La luce tende la mano a chi è disposto a farsi davvero aiutare.»\n\nE chiude sempre con un ribaltamento che riguarda noi: il punto, qui sulla Terra, non è giudicare l'altro — è guardare la frequenza che stiamo scegliendo noi, anche quando proviamo rabbia, odio o desiderio di vendetta. Perché il rancore che coltiviamo non punisce chi ci ha ferito: abbassa la nostra vibrazione, non la sua. ⚖️"},

  {id:"dio_religione",tema:"Dio & religione",label:"Elisa parla di Dio e di religione?",
   domande:["Elisa crede in Dio? Gli spiriti parlano di Dio?","Quello che dice Elisa è compatibile con la religione?","Esistono il paradiso e l'inferno della religione?","Devo pregare Dio? Cosa dice Elisa della fede","Dio esiste secondo Elisa?"],
   keys:["dio","religione","religioso","pregare","gesù","chiesa","fede","cattolica"],
   risposta:"Elisa ha un atteggiamento preciso su questo tema, e parte da un confine che lei stessa si è data: non parla mai in chiave religiosa. «Non voglio influenzare nessuno, e non è nemmeno mio compito. Io riferisco semplicemente ciò che vedo.» Non si mette sopra né contro nessuna fede: riporta la sua esperienza, e lascia a ciascuno la propria strada.\n\nDetto questo, ciò che riporta dialoga profondamente con il cuore di ogni religione. Della Luce — quella dimensione di amore incondizionato che attraversa tutte le sue canalizzazioni — parla continuamente; ed esistono, dice, energie ed entità di amore puro verso cui tendiamo.\n\nSull'immagine di Dio, la sua posizione è netta e bellissima: non un giudice. «C'è una cultura secondo cui dopo la morte saremo tutti davanti a un tribunale divino — ma è molto più coerente con le religioni stesse un Dio che prova solo amore e che tende la mano verso l'umanità, la quale può scegliere se prendere quella mano o no. Penso che questa sia la base di qualsiasi religione.»\n\nNiente inferno eterno, quindi, e niente condanna: al loro posto, lo specchio della coscienza e un amore che non chiude mai le porte (trovi la voce sulla giustizia per approfondire).\n\nE la preghiera? Per Elisa la preghiera è energia, ed energia d'amore: arriva, fa bene, accompagna — qualunque sia la forma e la fede in cui la reciti. Se hai una fede, ciò che Elisa racconta non te la toglie: semmai le dà respiro. 🙏🏻"},

  /* ---------- ELISA E LA MEDIANITÀ ---------- */
  {id:"chi_e_elisa",tema:"Chi è Elisa",label:"Chi è Elisa Soul Medium",
   domande:["Chi è Elisa Soul Medium?","Qual è la storia di Elisa, come ha capito di essere medium?","Da quando Elisa sente gli spiriti","Cosa ha fatto Elisa prima di diventare conosciuta","Elisa è una sensitiva vera? Qual è il suo percorso"],
   keys:["storia","diventata","sensitiva","bambina","percorso","conosciuta"],
   risposta:"Elisa, conosciuta come Elisa Soul Medium, è una sensitiva e medium italiana. Si definisce un tramite tra la dimensione terrena e quella spirituale — e ci tiene a una precisazione che dice tutto del suo approccio: «Io non faccio questo, io sono questo.» Non una guru, non una prescelta: una persona con una sensibilità che ha imparato ad accogliere.\n\nLa sua storia: percepisce presenze da quando ha memoria — i primi episodi intorno ai 5 anni, e a 7 anni quello che segna tutto: descrive alla madre un cugino defunto che non aveva mai conosciuto. Poi un'adolescenza di rifiuto, in cui prova a soffocare quella sensibilità per sentirsi «normale», senza riuscirci. La svolta arriva verso i 30 anni, con il trasferimento a Gran Canaria e l'incontro con persone — tra cui il marito, inizialmente scettico — che le danno il coraggio di accettarsi. Nel dicembre 2024 sceglie di uscire pubblicamente, affrontando anche attacchi e amicizie perdute.\n\nOggi ha all'attivo centinaia di consulti — e un dato che racconta molto: circa l'80% dei suoi clienti era inizialmente scettico, inclusi medici, psicologi e magistrati. Ha scritto il libro La Vita Oltre il Velo e ha fondato la community Oltre il Velo. Collabora con psicologi, perché per lei spiritualità e supporto psicologico sono complementari.\n\nLa sua cifra è la trasparenza: dichiara apertamente di non poter dimostrare scientificamente ciò che fa, rifiuta il sensazionalismo e i «veli di mistero» costruiti ad arte, e parla solo di ciò che vive direttamente. «Parlare di aldilà, per me, non significa parlare di morte. Significa parlare di vita.»"},

  {id:"metodo_connessione",tema:"Medianità & metodo",label:"Come avviene una canalizzazione",
   domande:["Come avviene una canalizzazione?","Come comunicano gli spiriti con Elisa","Come fa Elisa a vedere e sentire gli spiriti","Cosa succede durante una connessione medianica","Gli spiriti dicono il loro nome? Come arrivano le informazioni"],
   keys:["canalizzazione","canalizza","connessione","comunica","comunicano","arrivano","funziona"],
   risposta:"Elisa lo spiega senza nessun alone di mistero, perché è proprio la sua filosofia: togliere il sensazionalismo e raccontare come funziona davvero.\n\nQuando uno spirito comunica, non sempre lo fa con le parole: arrivano immagini, emozioni, sensazioni fisiche — e a volte, dice, «è come se vedessi attraverso i suoi occhi». Ogni medium riceve con sensi diversi: Elisa è visiva — le informazioni le arrivano come immagini e parole scritte, non come voci. Per questo, ad esempio, i nomi completi le arrivano raramente (più spesso le iniziali), mentre altri medium «uditivi» li sentono: non è una gara, sono sensibilità diverse, e lei lo riconosce con grande serenità.\n\nUna connessione ha tre fasi: la preparazione, la canalizzazione vera e propria, e il distacco — una fase delicata che può durare da mezz'ora a una giornata intera, a seconda dell'intensità. Ed è un lavoro che pesa: certe canalizzazioni sono emotivamente molto impegnative anche per lei.\n\nI punti fermi del suo metodo: non forza mai nulla — gli spiriti comunicano ciò che loro hanno bisogno di dire, non ciò che vorremmo sentirci dire, anche perché l'energia che usano per comunicare è limitata e la spendono per l'essenziale. Tutto è regolato dai permessi (a volte le viene detto: «basta, non mi è concesso andare oltre»). Le «visioni» non sono presenze fisiche ma ricostruzioni che lo spirito le proietta. E non predice il futuro: non è una veggente, e i consulti «per sapere cosa succederà» non li fa. Gli spiriti, ripete sempre, sono persone — e come persone, ognuno comunica a modo suo. 🔮"},

  {id:"medium_serio",tema:"Medianità & etica",label:"Come riconoscere un medium serio",
   domande:["Come si riconosce un medium serio da un ciarlatano?","Come capisco se un sensitivo è affidabile o un truffatore","È giusto pagare un medium?","Quali sono i segnali di una truffa spirituale","Elisa che regole etiche segue nei consulti"],
   keys:["serio","affidabile","truffa","truffatore","ciarlatano","riconoscere","pagare","soldi"],
   risposta:"Elisa è durissima su questo tema — «non mi paragonate a certe persone, perché c'è un abisso tra il mio approccio e il loro» — e proprio dal suo modo di lavorare si ricava una lista concreta di segnali per distinguere chi è serio da chi specula sul dolore.\n\nUn medium serio:\n\n• Non promette certezze né «prove a comando». Elisa dichiara apertamente che non può dimostrare scientificamente ciò che fa — chi invece garantisce risultati sicuri sta già mentendo.\n• Non ti cerca lui. Elisa non scrive mai in privato per proporre consulti. Chi ti contatta in DM offrendo «contatti col tuo caro» (spesso fingendosi un medium noto) è una truffa, sempre.\n• Non specula sull'urgenza e non ti lega a sé. Niente «rituali» da ripetere, niente paure instillate per farti tornare. Elisa fa un solo consulto per spirito: rispetta il percorso di chi è di là, invece di trasformare il lutto in un abbonamento.\n• È trasparente sui soldi: dove non c'è canalizzazione, non c'è pagamento — il rimborso se la connessione non avviene è parte della sua etica.\n• Non si sostituisce mai a medici e psicologi, e anzi indirizza al supporto professionale quando serve.\n• Niente sensazionalismo: diffida di chi costruisce «veli di mistero», scenografie inquietanti, poteri facili. La medianità seria, dice Elisa, è prima di tutto un grande lavoro su se stessi.\n\nE sul «se hai un dono dovresti farlo gratis»: Elisa risponde che dietro ci sono decenni di percorso, studio e fatica — vivere del proprio lavoro, fatto con onestà, non è speculare. Speculare è altro, e si riconosce dai punti qui sopra. 🛡️"},

  {id:"scettici",tema:"Critiche & confronto",label:"E chi non ci crede?",
   domande:["Cosa risponde Elisa agli scettici?","Vorrei crederci ma la mia parte razionale non ci riesce","Come fa Elisa a dimostrare quello che fa","Perché dovrei credere a una medium?","Come reagisce Elisa alle critiche e agli haters"],
   keys:["scettico","scettici","credere","crederci","prove","dimostrare","razionale","critiche"],
   risposta:"La risposta di Elisa agli scettici spiazza molti, perché non cerca mai di convincere: valida il dubbio. «Lo so, è normale che la razionalità non l'accetti: la mente si difende da ciò che non comprende, e non essendoci evidenze scientifiche è normale che si blocchi.»\n\nIl suo patto di onestà è questo: dichiara apertamente che la scienza, oggi, non può dimostrare ciò che fa — e che lei non può fare più di così. Quello che può fare, e fa, è portare elementi concreti: nei consulti arrivano spesso dettagli che la persona non conosceva e che vengono verificati dopo (storie del passato confermate da altri familiari, ad esempio). È il suo modo di «dimostrare almeno un po'». E un dato parla da solo: circa l'80% dei suoi clienti era inizialmente scettico — tra loro medici, psicologi, magistrati.\n\nCon chi dubita in buona fede, Elisa è accogliente: non spinge a credere, non si offende, risponde. Apprezza perfino le critiche argomentate — accetta spunti, ringrazia chi la mette in guardia (per esempio sulle trappole dell'ego), e ama dire che preferisce far riflettere piuttosto che piacere: «non sempre l'anima cresce attraverso ciò che è semplice da ascoltare».\n\nIl confine lo mette solo con chi insulta senza argomentare: lì chiede prove e argomenti, o blocca — non per le visualizzazioni, dice, ma per proteggere l'energia di chi la segue.\n\nE a chi sospetta il tornaconto risponde con i fatti: nessuna pubblicità ai consulti (mai sponsorizzati, e oggi di fatto fermi), trasparenza sui rimborsi, contenuti gratuiti. «Non ho nessun tornaconto nello spiegare queste cose: ci credo profondamente.» Il dubbio resta legittimo — per Elisa, può perfino essere l'inizio del cammino. 🤝"},

  {id:"sensibilita",tema:"Sensibilità & percorso",label:"Anch'io sento delle cose…",
   domande:["Anch'io sento delle cose, credo di essere sensibile: come capisco se è reale e come la sviluppo?","Come capisco se sono sensitivo o medium","Come si sviluppa la sensibilità","Anche io percepisco delle presenze, è normale?","Ho un dono come il tuo, come faccio a coltivarlo"],
   keys:["sensibile","sensibilità","sensitivo","sensitiva","percepisco","percepire","presenze","sviluppare","dono"],
   risposta:"Mi fa piacere che me lo chiedi, e parto da una cosa che ripeto spesso: il «sentire» non è un dono per pochi. È un'intuizione che appartiene a ogni persona — quella voce interiore che riconosce ciò che è autentico, ciò che è in sintonia con noi. La differenza è che crescendo, tra razionalità e abitudini sociali, tendiamo a chiudere quei canali. La domanda vera, allora, non è «sono speciale?», ma «perché, come esseri umani, abbiamo smesso di sentire?».\n\nCome capire se ciò che provi è reale? Qui ti invito alla prudenza, non all'eccitazione. Il primo passo non è cercare fenomeni o conferme, ma imparare a conoscerti davvero — la tua parte luminosa e anche la tua ombra. La medianità, prima ancora che «sentire i defunti», è un lavoro su di sé: sulle proprie emozioni, sui legami, sulle ferite. È un cammino lungo, di tutta una vita, non un interruttore che si accende.\n\nDiffida di chi ti promette poteri facili o scorciatoie. La sensibilità autentica si coltiva con calma — con il silenzio, la meditazione, l'ascolto — e va trattata con rispetto e responsabilità, mai con sensazionalismo.\n\nSe è qualcosa che senti tuo, coltivalo senza fretta e senza paura. E se ti capita di percepire cose che ti spaventano o ti pesano, non isolarti: parlane con qualcuno di fidato. Non sei in gara, e non sei solo in questo."},

  {id:"consulto",tema:"Operativo & consulti",label:"Il consulto: cos'è e quando ha senso",
   domande:["È giusto fare un consulto medianico? Come funziona e quando ha senso farlo?","Vorrei prenotare un consulto con te, come si fa?","Come funziona un consulto","Quando ha senso fare un consulto","È giusto cercare risposte da chi non c'è più"],
   keys:["consulto","consulti","medianico","prenotare","seduta"],
   risposta:"Ti rispondo con franchezza, perché ci tengo. «Giusto o sbagliato» non è il metro con cui la guardo. Un consulto va sentito, non è un obbligo — e se una persona può farne a meno, a volte è perfino meglio così. Lo ripeto da sempre: ha senso solo se c'è davvero un «cerchio rimasto aperto», qualcosa da chiudere. Mai per curiosità.\n\nPerché un consulto non è una magia che cancella il dolore. È un ponte: un momento di ascolto, di rispetto e di verità, che può aprire una porta — ma poi il cammino resta tuo, e quello nessuno può percorrerlo al posto tuo.\n\nCome funziona, in concreto? È una connessione: mi metto in ascolto e lascio che siano loro, i tuoi cari, a portare ciò che hanno bisogno di dirti. Non è uno spettacolo, e non prometto «prove» a comando: ti dico sempre con onestà che non posso dimostrare scientificamente quello che faccio, e sarei disonesta a sostenere il contrario.\n\nUn'ultima cosa, col cuore: in questo periodo i consulti sono di fatto fermi, con una lista d'attesa lunghissima. Per questo ho messo tanto nei contenuti e nel libro — spesso spero siano loro, più che altro, ad accompagnarti. E ricorda che gran parte del «contatto» non ha bisogno di me: parlare ai tuoi cari puoi farlo tu, ogni giorno."}

  ];

  prepara();
  return { rispondi:rispondi, byId:byId, MENU:MENU, AVVISO:AVVISO, count:BANK.length };
})();
